# Generated by Django 4.2.4 on 2025-10-15 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='odometer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_available',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='units_sold',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='demand_forecast',
        ),
        migrations.RemoveField(
            model_name='product',
            name='optimized_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_brand',
            field=models.TextField(default=0, max_length=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_grade',
            field=models.TextField(default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='station_name',
            field=models.TextField(default='station 1', max_length=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
