# Generated by Django 4.2.4 on 2025-10-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_rename_description_product_odometer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fuel_brand',
            field=models.TextField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='station_name',
            field=models.TextField(default='station 1', max_length=50),
        ),
    ]
